import { NextRequest, NextResponse } from 'next/server';
import crypto from 'node:crypto';
import {
  extractClientIp,
  hashVisitorIp,
  getMaskedIpIdentifier,
  isBotOrCrawler,
  sanitizePath,
  sanitizeReferrer,
} from '@/lib/analytics/visitor';
import { recordPageVisit } from '@/lib/db';
import { getServerSession } from '@/lib/auth';

const VISITOR_COOKIE_NAME = 'tff_vid';

// In-memory rate limiter to prevent spam or runaway tracking loops
const rateLimitMap = new Map<string, { count: number; resetTime: number }>();

function checkRateLimit(key: string, limit = 60, windowMs = 60000): boolean {
  const now = Date.now();
  const entry = rateLimitMap.get(key);

  if (!entry || now > entry.resetTime) {
    rateLimitMap.set(key, { count: 1, resetTime: now + windowMs });
    // Clean up expired keys periodically
    if (rateLimitMap.size > 2000) {
      for (const [k, v] of rateLimitMap.entries()) {
        if (now > v.resetTime) rateLimitMap.delete(k);
      }
    }
    return true;
  }

  if (entry.count >= limit) {
    return false;
  }

  entry.count++;
  return true;
}

export async function POST(request: NextRequest) {
  try {
    const userAgent = request.headers.get('user-agent');

    // 1. Filter out automated search bots and web crawlers
    if (isBotOrCrawler(userAgent)) {
      return NextResponse.json({ ok: true, ignored: 'bot' });
    }

    const body = await request.json().catch(() => null);
    if (!body || typeof body !== 'object') {
      return NextResponse.json({ error: 'Valid payload required' }, { status: 400 });
    }

    const { path: rawPath, referrer: rawReferrer } = body;

    // 2. Validate and sanitize page path
    const path = sanitizePath(rawPath);
    if (!path) {
      return NextResponse.json({ ok: true, ignored: 'invalid_or_internal_path' });
    }

    // 3. Exclude visits generated by managers browsing the manager dashboard
    const session = await getServerSession();
    if (session?.isManager && path.startsWith('/manager')) {
      return NextResponse.json({ ok: true, ignored: 'manager_activity' });
    }

    // 4. Extract client IP from trusted headers and hash using HMAC-SHA256
    const clientIp = extractClientIp(request.headers);
    const visitorHash = hashVisitorIp(clientIp);

    // 5. Rate limiting: max 60 visits per minute per visitor
    if (!checkRateLimit(visitorHash)) {
      return NextResponse.json({ ok: true, rateLimited: true });
    }

    // 6. First-party visitor cookie identification
    let visitorSessionId = request.cookies.get(VISITOR_COOKIE_NAME)?.value;
    let isNewCookie = false;

    if (!visitorSessionId || visitorSessionId.length > 64) {
      visitorSessionId = `vid_${crypto.randomBytes(16).toString('hex')}`;
      isNewCookie = true;
    }

    const maskedIp = getMaskedIpIdentifier(clientIp, visitorHash);
    const referrer = sanitizeReferrer(rawReferrer);

    // 7. Persist visit record to server database
    const result = recordPageVisit({
      visitorHash,
      maskedIp,
      path,
      referrer,
      userAgent: userAgent || undefined,
      visitorSessionId,
    });

    const response = NextResponse.json({
      ok: true,
      debounced: result.debounced,
    });

    // 8. Attach first-party visitor cookie if new
    if (isNewCookie) {
      response.cookies.set(VISITOR_COOKIE_NAME, visitorSessionId, {
        httpOnly: true,
        secure: process.env.NODE_ENV === 'production',
        sameSite: 'lax',
        path: '/',
        maxAge: 365 * 24 * 60 * 60, // 1 year
      });
    }

    return response;
  } catch (error) {
    console.error('Visitor tracking error:', error);
    return NextResponse.json({ error: 'Failed to record visit' }, { status: 500 });
  }
}
