/**
 * Optional: vendor the AI model assets so nothing is fetched from a third-party CDN.
 *
 * Run with:  node scripts/vendor-models.mjs
 *
 * By default, two tools download model data on first use:
 *   - background removal: about 40 MB of ONNX segmentation weights
 *   - OCR: language data for the language you select, a few MB per language
 *
 * Neither of those downloads ever contains your file - the file is processed
 * locally either way. But if you would rather not have a third-party origin in
 * your Content-Security-Policy, or you want the first use of those tools to be
 * fast on a slow connection, run this script once, upload `public/models/` with
 * the rest of the site, and set:
 *
 *   NEXT_PUBLIC_BG_REMOVAL_ASSET_BASE=   (your origin, e.g. https://toolino-one.vercel.app)
 *   NEXT_PUBLIC_OCR_ASSET_BASE=          (your origin)
 *
 * `public/models/` is git-ignored because it is large and regenerable.
 */

import { createWriteStream, existsSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MODELS_DIR = join(ROOT, 'public', 'models');

/** Background-removal model bundle, matching the installed package version. */
const BG_REMOVAL_VERSION = '1.7.0';
const BG_REMOVAL_BASE = `https://staticimgly.com/@imgly/background-removal-data/${BG_REMOVAL_VERSION}/dist`;

/**
 * The files the background-removal package requests at runtime.
 * The ONNX weights are fetched per resolution; `isnet` is the default model.
 */
const BG_REMOVAL_FILES = [
  'resources.json',
  'isnet_quint8.onnx',
  'isnet_fp16.onnx',
  'isnet.onnx',
];

/** OCR languages worth pre-vendoring. Add your own; each is a few MB. */
const OCR_LANGUAGES = ['eng', 'deu', 'fra', 'spa', 'ita', 'por', 'nld', 'pol', 'rus'];
const OCR_BASE = 'https://cdn.jsdelivr.net/npm/@tesseract.js-data';

/** Measured download progress without a dependency. */
async function download(url, destination) {
  if (existsSync(destination) && statSync(destination).size > 0) {
    console.log(`  skip   ${destination.replace(ROOT + '/', '')} (already present)`);
    return true;
  }

  mkdirSync(dirname(destination), { recursive: true });

  let response;
  try {
    response = await fetch(url, { redirect: 'follow' });
  } catch (error) {
    console.warn(`  FAILED ${url} - ${error instanceof Error ? error.message : error}`);
    return false;
  }

  if (!response.ok || !response.body) {
    console.warn(`  FAILED ${url} - HTTP ${response.status}`);
    return false;
  }

  await pipeline(Readable.fromWeb(response.body), createWriteStream(destination));
  const size = statSync(destination).size;
  console.log(`  saved  ${destination.replace(ROOT + '/', '')} (${(size / 1024 / 1024).toFixed(1)} MB)`);
  return true;
}

// --------------------------------------------------------------------- main

console.log('vendor-models: downloading model assets into public/models/');
console.log('vendor-models: this is a one-off; the files are then served from your own origin.');
console.log('');

mkdirSync(MODELS_DIR, { recursive: true });

let downloaded = 0;
let failed = 0;

console.log('Background removal (about 40 MB in total):');
for (const file of BG_REMOVAL_FILES) {
  const ok = await download(
    `${BG_REMOVAL_BASE}/${file}`,
    join(MODELS_DIR, 'background-removal', file)
  );
  if (ok) downloaded += 1;
  else failed += 1;
}

console.log('');
console.log('OCR language data:');
for (const language of OCR_LANGUAGES) {
  const ok = await download(
    `${OCR_BASE}/${language}/4.0.0_best_int/${language}.traineddata.gz`,
    join(MODELS_DIR, 'tesseract', `${language}.traineddata.gz`)
  );
  if (ok) downloaded += 1;
  else failed += 1;
}

// A short README so the directory is self-explanatory if someone stumbles on it.
writeFileSync(
  join(MODELS_DIR, 'README.md'),
  `# Vendored model assets

Generated by \`node scripts/vendor-models.mjs\`. Not committed to git.

Serve this directory with the rest of the site, then set:

\`\`\`
NEXT_PUBLIC_BG_REMOVAL_ASSET_BASE=<your origin>
NEXT_PUBLIC_OCR_ASSET_BASE=<your origin>
\`\`\`

Once those are set you can remove \`cdn.jsdelivr.net\`, \`unpkg.com\` and
\`staticimgly.com\` from the Content-Security-Policy in
\`deploy/cloudfront/response-headers-policy.json\`.

These are model weights and language data. Your files are never sent to any of
these origins - the tools process your content locally in both configurations.
`,
  'utf8'
);

console.log('');
console.log(`vendor-models: ${downloaded} file(s) ready, ${failed} failed.`);
if (failed > 0) {
  console.log('vendor-models: some downloads failed. Re-run to retry only the missing files.');
}
console.log('');
console.log('Next steps:');
console.log('  1. Upload public/models/ with the rest of out/ (the deploy script does this).');
console.log('  2. Set NEXT_PUBLIC_BG_REMOVAL_ASSET_BASE and NEXT_PUBLIC_OCR_ASSET_BASE.');
console.log('  3. Rebuild, and tighten the CSP in deploy/cloudfront/response-headers-policy.json.');
